(function(){var g=void 0,h=true,i=null,k=false,m,n=this;function aa(a,b){function c(){}c.prototype=b.prototype;a.Q=b.prototype;a.prototype=new c;a.prototype.constructor=a};function ba(a,b){var c;c=new Image(1,1);if(b)c.onerror=b;c.src=a}function ca(){for(var a="",b=0;b<16;b++)a+=Math.random();return a}function p(a,b){var c="",d=da(encodeURIComponent(a));d.splice(b||5,d.length);q(d,function(a){if(a==0)a="A";else{a>>>=0;for(var b="",d;a>0;)d=a%64,b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-".charAt(d)+b,a>>>=6;a=b}c+=a});return c}
function da(a){a+=String.fromCharCode(128);for(var b=[1518500249,1859775393,2400959708,3395469782],c=1732584193,d=4023233417,e=2562383102,f=271733878,l=3285377520,j=[],o,w,v,J,K,Y=Math.ceil((a.length/4+2)/16),T=[Y],A=0,u;A<Y;A++){T[A]=[];for(o=0;o<16;o++)T[A][o]=a.charCodeAt(A*64+o*4)<<24|a.charCodeAt(A*64+o*4+1)<<16|a.charCodeAt(A*64+o*4+2)<<8|a.charCodeAt(A*64+o*4+3)}A=(a.length-1)*8;a=Y-1;T[a][14]=Math.floor(A/Math.pow(2,32));T[a][15]=A&4294967295;for(A=0;A<Y;A++){for(u=0;u<16;u++)j[u]=T[A][u];
for(u=16;u<80;u++)j[u]=(j[u-3]^j[u-8]^j[u-14]^j[u-16])<<1|(j[u-3]^j[u-8]^j[u-14]^j[u-16])>>>31;a=c;o=d;w=e;v=f;J=l;for(u=0;u<80;u++)K=Math.floor(u/20),K=(a<<5|a>>>27)+(K==0?o&w^~o&v:K==1?o^w^v:K==2?o&w^o&v^w&v:o^w^v)+J+b[K]+j[u]&4294967295,J=v,v=w,w=o<<30|o>>>2,o=a,a=K;c=c+a&4294967295;d=d+o&4294967295;e=e+w&4294967295;f=f+v&4294967295;l=l+J&4294967295}return[c,d,e,f,l]}
function ea(a){var b=n.navigator,c=n.window.screen,d=[b.userAgent,b.platform,(new Date).getTimezoneOffset(),c.width+c.height+c.colorDepth];q(b.plugins,function(a){d.push(a.name+a.description+a.filename+a[0].type)});b=n.performance;d=d.concat([b&&b.now?b.now():"",document.title,n.location.href,r(),ca()]);return d.concat(a||[]).join()}function s(a,b,c){var d=Array.prototype.slice,e=d.call(arguments,2);return function(){return a.apply(b,e.concat(d.call(arguments)))}}
function t(a){return typeof a!=="undefined"}function x(a){return a.replace(/^www\./,"")}function y(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)}function fa(a,b){var c=n;c.removeEventListener?c.removeEventListener(a,b,k):c.detachEvent&&c.detachEvent("on"+a,b)}function z(a){return typeof a==="number"}function B(a){return typeof a==="string"}function ga(a){a=new Date(+a);return Date.UTC(a.getFullYear(),a.getMonth(),a.getDate())}
function r(){return(new Date).getTime()}function ha(a){return encodeURIComponent(a)}function C(a){return!!a&&a.constructor===Object}function ia(a,b){if(!C(a)||!C(b))return a===b;var c=0,d=h;q(a,function(a,e){c++;return d=a===b[e]});if(!d)return k;var e=0;q(b,function(){e++});return c===e}function q(a,b){if(C(a)===h)for(var c in a){if(a.hasOwnProperty(c)&&b(a[c],c)===k)break}else{c=0;for(var d=a.length;c<d;c++)if(b(a[c],c)===k)break}}
function ja(a,b){for(var c=0,d=a.length;c<d;c++)if(b(a[c]))return c;return-1}function ka(a){if(C(a)===k)return"";var b=[];q(a,function(a,d){b.push(encodeURIComponent(d)+"::"+encodeURIComponent(a))});return b.join("&")}function la(a){C(a)===h&&(a="");var b={};q(a.split("&"),function(a){a=a.split("::");a.length===2&&(b[decodeURIComponent(a[0])]=decodeURIComponent(a[1]))});return b}
function ma(a,b){if(a===b)return 0;if(a.length===0)return b.length;if(b.length===0)return a.length;for(var c=[],d=0,e=b.length;d<=e;d++)c[d]=[d];for(var f=0,l=a.length;f<=l;f++)c[0][f]=f;for(var j,o,w,d=1;d<=e;d++)for(f=1;f<=l;f++)j=d-1,o=f-1,w=c[j][o],b.charAt(j)==a.charAt(o)?c[d][f]=w:(o=c[d][o]+1,j=c[j][f]+1,w+=2,c[d][f]=Math.min(o,j,w));return c[b.length][a.length]}var na;function oa(a,b,c){b=b||"*";c=c||document;if("querySelectorAll"in c)return c.querySelectorAll(b+"["+a+"]");for(var d=[],b=c.getElementsByTagName(b),c=b.length;c--;)b[c].getAttribute(a)&&d.push(b[c]);return d}function D(a,b){var c=i;b&&(c=b.getAttribute(a));if(c===i){var d=oa(a,"*",b);d.length!==0&&(c=d[0].getAttribute(a))}return c}function pa(a,b,c){return a===g?k:c===g&&a.getAttribute(b)||a.getAttribute(b)===c?a:a===document.body?k:pa(a.parentNode,b,c)}
function qa(a,b,c){a="page"+a+"Offset";b="scroll"+b;if(c&&(c=oa("data-cb-scroll-element"))&&c.length)return c[0][b];if(z(n[a]))return n[a];else if(document.body&&document.body[b])return document.body[b];else if(document.documentElement[b])return document.documentElement[b];return 0}function ra(a){var b=document,b=b[b.compatMode==="CSS1Compat"?"documentElement":"body"]["client"+a]||0;window["inner"+a]&&(b=Math.min(window["inner"+a],b));return b}function sa(){return ra("Height")}
function ta(a){a="scroll"+a;return Math.max(document.body[a],document.documentElement[a])||0}function ua(a,b,c){var d=a.ownerDocument.documentElement,e=0,f=t(c)?c+1:-1;B(b)?(b=b.toLowerCase(),c=function(a){return(a=a.nodeName)&&a.toLowerCase()===b}):c=b;for(;a&&a!==d&&e!==f;){if(c(a))return a;a=a.parentNode;e++}return i}function va(a){return a.nodeName&&a.nodeName.toLowerCase()==="a"&&(!a.namespaceURI||a.namespaceURI==="http://www.w3.org/1999/xhtml")}
function wa(a){a=a||window.event;return!a?i:ua(a.target||a.srcElement,va,10)};var E={},xa=1,ya="a";function F(a,b,c){xa++;E[a]=E[a]||{};E[a][xa]=[b,c];return xa}function G(a){if(B(a))E[a]=g,delete E[a];else if(z(a)){var b=h;q(E,function(c){q(c,function(d,e){if(parseInt(e,10)===a)return c[e]=g,delete c[e],b=k});return b})}}function H(a,b){if(E[a]){var c=arguments.length>1?Array.prototype.slice.call(arguments,1):[];q(E[a],function(a){var b;a&&a.length===2&&(b=a[0],a=a[1],b.apply(a,c))})}};var I={};
I.k=function(){I.Ta?I.Da("pageload"):(I.Fb=[{target:n,event:"scroll"},{target:document.body,event:"keydown"},{target:document.body,event:"mousemove"},{target:n,event:"resize"},{target:document.body,event:"mousedown"}],I.Ja=i,I.cb=k,I.ma=i,I.ub={},q(I.Fb,function(a){var b=a.event;y(a.target,b,function(a){I.Da.call(I,b,a)})}),F("f",function(){I.Da("focus")}),I.Da("pageload"),y(document.body,"click",function(a){(a=wa(a))&&H("c",a)},h),y(document.body,"contextmenu",function(a){(a=wa(a))&&H("r",a)}),I.Ta=
h)};I.Jb=function(){var a,b=I.ub.keydown;if(b===g)return k;b=r()-b;return b<=(a||15E3)&&b>=0};I.hb=100;I.Da=function(a,b){if(!b)b=window.event;if(b&&a==="keydown"){var c=b.keyCode?b.keyCode:b.which;if(c===32||c>36&&c<41)a="scroll"}I.uc(a);I.Ja===i?I.zb():I.cb=h};I.uc=function(a){I.ub[a]=r()};I.zb=function(){I.Ja=n.setTimeout(I.Pb,I.hb);H(ya);I.ma!==i&&n.clearTimeout(I.ma);I.ma=n.setTimeout(function(){H("i");n.clearTimeout(I.ma);I.ma=i},5E3+I.hb)};
I.Pb=function(){n.clearTimeout(I.Ja);I.Ja=i;if(I.cb)I.cb=k,I.zb()};var za=/[?&]__cb_debug=([^&]+)/i;var Aa,Ba,Ca,Da,Ea;(function(){var a,b;q(["","moz","o","ms","webkit"],function(c){a=(c+"Hidden").charAt(0).toLowerCase()+(c+"Hidden").slice(1);if(typeof n.document[a]==="boolean")return b=c,k});b!==g&&(Da=a,Ea=(b+"VisibilityState").charAt(0).toLowerCase()+(b+"VisibilityState").slice(1),Ca=b+"visibilitychange")})();var Fa=k;function Ga(){Fa=Ea&&n.document[Ea]==="prerender"?h:k}function Ha(){Ba=h;H("f")}function Ia(){Ba=k;H("b")}
function Ja(a,b,c){n.addEventListener?n.addEventListener(a,c,k):n.document.attachEvent&&n.document.attachEvent(b,c)}function Ka(){var a=h;n.document.hasFocus&&(a=n.document.hasFocus());var b=k;Da&&(b=n.document[Da]);return a&&!b}function La(){Ka()?Ha():Ia()}function Ma(a){Ga();if(Fa){var b=k,c=function(){b||(Ga(),Fa||(b=h,a(),n.window.setTimeout(function(){n.document.removeEventListener(Ca,c,k)},100)))};n.document.addEventListener(Ca,c,k)}else a()};function L(){this.a=n._sf_async_config||{};this.mb=s(this.xb,this)}L.prototype.k=function(){this.Fa=0};L.prototype.xb=function(){};L.prototype.qa=function(a){Fa||ba(a,this.mb)};L.prototype.O=function(){this.mb=i};function Na(a){var b={};a&&(a.charAt(0)=="?"&&(a=a.substring(1)),a=a.replace("+"," "),q(a.split(/[&;]/g),function(a){a=a.split("=");b[decodeURIComponent(a[0])]=decodeURIComponent(a[1])}));return b}function Oa(a,b){var c="",d=n.location.href.split("?");if(d.length){var d=Na(d[1]),e=b||a;d[e]&&(c=d[e])}return c}function Pa(a,b){return!b?h:a==="http:"&&b==="80"||a==="https:"&&b==="443"}
function Qa(a,b){var c=[];q(b,function(b){var e=a[b];t(e)&&(Object.prototype.toString.call(e)==="[object Array]"?q(e,function(a){c.push(b+"="+a)}):C(e)?q(e,function(a,b){c.push(b+"="+a)}):((e+"").length||b=="r")&&c.push(b+"="+e))});c.push("_");return c.join("&")}
function Ra(a){var b={hostname:"",pathname:"",search:"",protocol:"",port:"",hash:""};if(!a)return b;var c=document.createElement("a"),d=n.location;if(!/^https?:/.test(a)&&a.indexOf("javascript:")!==0)if(a.indexOf("//")===0)a=d.protocol+a;else if(a.indexOf("/")===0)var e=Pa(d.protocol,d.port)?"":d.port,a=d.protocol+"//"+d.hostname+(e?":"+e:"")+a;else{var e=document.baseURI||d.href,f=e.indexOf("?");f===-1&&(f=e.indexOf("#"));if(f===-1)f=e.length;f=e.lastIndexOf("/",f);a=f===-1?"/"+a:e.substr(0,f)+"/"+
a}c.href=a;b.hostname=c.hostname;b.pathname=c.pathname;b.search=c.search;b.protocol=c.protocol;b.port=c.port;b.hash=c.hash;if(b.pathname.charAt(0)!=="/")b.pathname="/"+b.pathname;if(b.hostname==="")b.hostname=d.hostname;if(b.protocol==="")b.protocol=d.protocol;if(b.protocol==="javascript:")b.pathname="",b.hostname="",b.port="",b.hash="";if(Pa(b.protocol,b.port)||b.port==="0")b.port="";return b}
function Sa(a){var b=a.protocol;a.hostname&&(b+="//"+a.hostname,a.port&&(b+=":"+a.port));return b+a.pathname+a.search+a.hash}function Ta(){var a=0,b=(n.location.search||"").match(za);b&&b[1]&&(a=parseInt(b[1],10));return a};function M(a,b,c){a[b]=a[b]||c}function Ua(a){q(document.getElementsByTagName("script"),function(b){if(b.src.match(/chartbeat.js/))return b=Na(b.src.split("?")[1]),M(a,"uid",b.uid),M(a,"domain",b.domain),k})}function Va(a,b){return a[b]?encodeURIComponent(a[b]):""}function Wa(a){var b={};q(a,function(a,d){d.charAt(0)=="_"&&(b[d]=a)});return b};function N(a){var b=a===document.documentElement?a.scrollHeight:a.offsetHeight,c=a.offsetWidth;if(b<=1||c<=1){var d=Xa(a,["overflow","overflow-x","overflow-y"]);d.overflow==="hidden"||d["overflow-x"]==="hidden"||d["overflow-y"]==="hidden"||q(a.getElementsByTagName("iframe"),function(a){var d=a.offsetHeight,a=a.offsetWidth;if(d>1&&a>1)return b=d,c=a,k})}return{height:b,width:c}}function Ya(a){a=N(a);return a.height*a.width}
function Za(a){var b;"contains"in document.documentElement&&!document.documentElement.contains(a)?b=k:(b=N(a),b=b.height>1&&b.width>1);if(!b)return k;b=Xa(a,["visibility","display","overflow","opacity"]);if(b.visibility=="hidden"||b.display=="none"||b.opacity=="0")return k;if(b.overflow=="hidden"&&(a.offsetHeight==0||a.offsetWidth==0))return k;b=h;for(var c=a.parentElement;c&&b;){var d;if(c.scrollHeight===c.clientHeight&&c.scrollWidth===c.clientWidth)d=k;else{var e=Xa(c,["overflow","overflow-x","overflow-y"]);
d=e.overflow;var f=e["overflow-x"],e=e["overflow-y"];d=d==="auto"||d==="scroll"||f==="auto"||f==="scroll"||e==="auto"||e==="scroll"}d&&(b=$a(a,c));c=c.parentElement}return b&&$a(a,i)}function $a(a,b){var c,d;if(b){var e=N(b);c=e.width;d=e.height}else c=ra("Width"),d=sa();var f=N(a),e=f.height,f=f.width,l=ab(a,b),j=l.y,l=l.x;c=Math.min(l+f,f,c,c-l);d=Math.min(j+e,e,d,d-j);if(c<0||d<0)return k;e*=f;return c*d>=(e>=242500?0.3:0.5)*e}
function ab(a,b,c){for(var d=a.offsetLeft,e=a.offsetTop,f=k,l=c?0:qa("X","Left",g),j=c?0:qa("Y","Top",g),o=a.offsetParent;a&&a!==b&&a!==document.body;){if(a===o)d+=a.offsetLeft,e+=a.offsetTop,o=a.offsetParent;c||(d-=a.scrollLeft,e-=a.scrollTop);if(Xa(a,["position"]).position==="fixed"){f=h;break}a=a.parentElement}c||(d-=b?b.scrollLeft:l,e-=b?b.scrollTop:j);f&&(d+=l,e+=j);return{x:d,y:e}}
function Xa(a,b){var c={},d,e;n.getComputedStyle?d=n.getComputedStyle(a,i):a.currentStyle?e="currentStyle":a.style&&(e="style");q(b,function(b){c[b]=d?d[b]||d.getPropertyValue(b):a[e][b]});return c};function bb(a,b){this.M=a;this.lb=b;this.ba=i;this.ja={rb:k,frame:k};this.Ib=F(ya,this.update,this)}bb.prototype.update=function(){cb(this,this.lb())};
function cb(a,b){var c=b.Kb;if(c){var d;if(a.ba)d=document.getElementById(a.ba);else{a.ba="engagementLog-"+a.M+"-"+p(ca());d=document.createElement("div");d.setAttribute("id",a.ba);document.body.appendChild(d);var e=c.getAttribute("style")||"",f=Xa(c,["position"]).position,f=f==="fixed"||f==="absolute"||f==="relative"?"":"position: relative;";e+="box-shadow: 0px 0px 0px 3px #49A2DC; z-index: 2000;"+f;c.setAttribute("style",e);var l="box-shadow: 0px 0px 0px 3px #5BC3BD, 10px 5px 5px #C8DAE8; z-index: 2000;"+
f;d.onmouseover=function(){c.setAttribute("style",l)};d.onmouseout=function(){e?c.setAttribute("style",e):c.removeAttribute("style")};y(d,"click",function(){a.ec=h})}d.innerHTML="";if(a.ec)d.setAttribute("style","display: none;");else{var j=ab(c),f=j.y,j=j.x;f+=qa("Y","Top",g);j+=qa("X","Left",g);d.setAttribute("style","background-color: #F1F7FB; z-index: 9000000; position: absolute; padding: 10px; border-radius: 5px; font-size: 12px; color: #658BA1; border: 1px solid #C8DAE8; margin: 3px; font-family: 'Proxima-Nova','Helvetica Neue',Helvetica,Arial,sans-serif; top: "+
f+"px; left: "+j+"px;");j=b.Lb;O("Ad Name: ",j.an+" ["+j.aw+"x"+j.ah+"]",d);(f=j.ac)&&O("Campaign: ",f,d);(f=j.av)&&O("Creative: ",f,d);O("Viewable: ",j.aV+"",d);d.appendChild(document.createElement("br"));var f=b.Rb,o=Za(f);O((o?"In ":"Out Of ")+" View","",d);o&&O("in view intervals: ",b.yc+"",d);O("Engaged Time: ",j.aE+" seconds",d);if(f!==c)a.Pa?(d=document.getElementById(a.Pa))&&c.removeChild(d):a.Pa="creativeContainer-"+a.M+"-"+p(ca()),d=document.createElement("div"),d.setAttribute("id",a.Pa),
j=ab(f,c),f=N(f),d.setAttribute("style","position: absolute; border-radius: 5px; border: 2px solid #00FFAD; background: transparent; top: "+j.y+"px; left: "+j.x+"px; height: "+f.height+"px; width: "+f.width+"px; margin: 0px; padding: 0px; z-index: 1000000;"),f=document.createElement("div"),f.setAttribute("style","position: absolute; right: 0px; bottom: 0px; font-size: 20px; background-color: white; padding: 10px;"),f.textContent=""+(a.ja.rb?"IAB ":"")+(a.ja.frame?"iframe ":""),d.appendChild(f),c.appendChild(d)}}}
function O(a,b,c){var d=document.createElement("div"),e=document.createElement("span");e.setAttribute("style","font-weight: bold;");e.textContent=a;d.textContent=b;d.insertBefore(e,d.firstChild);c.appendChild(d)}bb.prototype.O=function(){G(this.Ib);this.ja=this.lb=i;if(this.ba){var a=document.getElementById(this.ba);(a.parentElement?a.parentElement:a.parentNode).removeChild(a)}};var P={jb:{IDLE:0,Bc:1,Ac:2,ib:3},P:0};P.k=function(){if(!P.Ta)F(ya,P.Xb,P),F("i",P.$b,P),F("f",P.Zb,P),F("b",P.Yb,P),P.Ta=h};P.qb=function(){return P.P};P.Xb=function(){P.P===1?P.$(3):P.P===0&&P.$(2)};P.$b=function(){P.P===3?P.$(1):P.P===2&&P.$(0)};P.Zb=function(){(P.P===0||P.P===2)&&P.$(3)};P.Yb=function(){P.P===3?P.$(2):P.P===1&&P.$(0)};P.$=function(a){P.P=a;H("s",a)};function db(a,b){this.Ra=a||g;this.pa=b||g;this.fa=this.S=0}m=db.prototype;m.k=function(){this.fa=this.S=0;this.ta=i;this.rc=F("s",this.ka,this);this.ka(P.qb())};m.ka=function(a){n.clearInterval(this.ta);this.ta=i;if(a===P.jb.ib)this.ta=n.setInterval(s(this.fc,this),1E3)};m.fc=function(){if(this.Ra===g||this.Ra())this.S++,this.fa++,this.pa&&this.pa()};m.terminate=function(){n.clearInterval(this.ta);this.ta=i;G(this.rc)};m.O=function(){this.terminate();this.pa=this.Ra=g};function Q(a,b,c){L.call(this);this.F=a;this.mc=b;this.M=a.getAttribute("data-cb-ad-id")||a.id||"";this.Ka=s(this.Ka,this);this.kb=0;var d=this;this.X=new db(function(){eb(d);return Za(d.H)},s(this.pa,this));if(c)this.N=new bb(this.M,function(){return{Kb:d.F,Rb:d.H,yc:d.va,Lb:fb(d)}});this.k()}aa(Q,L);
Q.prototype.k=function(){Q.Q.k.call(this);this.kb++;this.J={};this.J.campaignId="";this.J.creativeId="";this.J.placementId="";this.J.siteId="";this.J.server_height="";this.J.server_width="";this.J.lineId="";this.H=this.F;this.Sa=this.Qa=k;eb(this);this.Eb=k;this.eb={};this.X.k();this.Db=k;this.va=0;this.aa=i;this.xc=F("s",this.ka,this);this.ka(P.qb())};Q.prototype.ka=function(a){if(this.aa!==i)n.clearTimeout(this.aa),this.aa=i;this.va=0;if(a===P.jb.ib)this.aa=n.setTimeout(this.Ka,100)};
Q.prototype.Ka=function(){if(Za(this.H)){if(this.va++,this.va>=10){this.Db=h;gb(this);H("p");return}}else this.va=0;this.aa=n.setTimeout(this.Ka,100);this.N&&this.N.update()};function gb(a){G(a.xc);n.clearTimeout(a.aa);a.aa=i}Q.prototype.pa=function(){H("e",hb(this),this.F);this.Eb&&H("z",this.eb,1);this.N&&this.N.update()};var ib={300:{250:1,600:1,1050:1},180:{150:1},160:{600:1},728:{90:1},970:{90:1,66:1,250:1,415:1,550:1},120:{60:1},88:{31:1},62:{88:1},196:{31:1}};
function eb(a){var b=n._sf_async_config;if(b&&(b=b.creativeDetection,b===k||B(b)&&b!=="iab"))return;var c=Ya(a.F);if(a.H!==a.F)if(b=Ya(a.H),b>c)a.H=a.F;else if(b>0)return;q(["iframe","embed","object","img","div"],function(b){q(a.F.getElementsByTagName(b),function(b){var d=N(b);if(!(d.height*d.width>c)&&ib[d.width]&&ib[d.width][d.height]){a.H=b;if(a.N)a.N.ja.rb=h;return k}});return a.H===a.F})}
function jb(a,b,c){a.J=b;a.Sa=!!c;if(a.Sa){var d=h,e=n._sf_async_config;if(e&&(e=e.creativeDetection,e===k||B(e)&&e!=="iframe"))d=k;if(d&&Ya(c)>0&&(a.H=c,a.N))a.N.ja.frame=h}H("p");if(b=b.vizu)a.Eb=h,a.eb=la(b),H("z",a.eb,a.X.S)}function R(a,b){return a.J?a.J[b]:""}function hb(a){var b={id:a.M,engagedSeconds:a.X.S};b.campaignId=R(a,"campaignId");b.creativeId=R(a,"creativeId");return b}
function fb(a){var b={};b.at=a.Ec;b.an=a.M;b.as=a.Fa;b.aj=240;b.aE=a.X.S;if(a.H){var c=ab(a.H,g,h);b.ax=c.x;b.ay=c.y;c=N(a.H);b.aw=c.width;b.ah=c.height}b.aV=a.Db;b.ao=a.kb;b.ac=R(a,"campaignId");b.av=R(a,"creativeId");b.aP=R(a,"placementId");b.aS=R(a,"siteId");b.aW=R(a,"server_width");b.aH=R(a,"server_height");b.aL=R(a,"lineId");b.exclude=a.Qa;return b}
function kb(a){var b=encodeURIComponent(a.an),c=a.aE,d=a.ax,e=a.ay,f=a.aw,l=a.ah,j=encodeURIComponent(a.av||""),o=encodeURIComponent(a.ac||""),w=encodeURIComponent(a.aP||""),v=encodeURIComponent(a.aS||""),J=encodeURIComponent(a.aH||""),K=encodeURIComponent(a.aW||""),Y=encodeURIComponent(a.aL||""),T=a.ao,A=a.aR||"0",u=a.aV?"1":"0";a.exclude&&(o="");return b+"="+[c,d,e,f,l,o,j,T+"."+A,u,w,v,J,K,Y].join("::")}
Q.prototype.ua=function(){if(!this.Sa){var a=this.F,b={};b.campaignId=D("data-cb-campaign-id",a)||"";b.creativeId=D("data-cb-creative-id",a)||"";b.placementId=D("data-cb-placement-id",a)||"";b.siteId=D("data-cb-site-id",a)||"";b.server_height=D("data-cb-creative-height",a)||"";b.server_width=D("data-cb-creative-width",a)||"";b.lineId=D("data-cb-line-id",a)||"";if(D("data-cb-exclude",a))this.Qa=h;ia(b,this.J)||jb(this,b)}};Q.prototype.reset=function(){gb(this);this.X.terminate();this.k()};
Q.prototype.O=function(){Q.Q.O.call(this);gb(this);n.clearInterval(this.Dc);this.X.O();this.mc=this.J=this.H=this.F=this.X=i;this.N&&this.N.O()};var S={};S.Ob=function(){try{S.create("_cb_test","1",1);var a=S.q("_cb_test");S.remove("_cb_test");return a==="1"}catch(b){return k}};S.q=function(a){a+="=";var b="";q(document.cookie.split(";"),function(c){for(;c.charAt(0)===" ";)c=c.substring(1,c.length);if(c.indexOf(a)===0)return b=c.substring(a.length,c.length),k});return b};
S.create=function(a,b,c){var d=n._sf_async_config;if(d&&d.noCookies)return"";d=new Date;d.setTime(r()+c*1E3);a=a+"="+b+("; expires="+d.toGMTString())+"; path=/";return document.cookie=a};S.remove=function(a){return S.q(a)?S.create(a,"",-86400):""};var U={};U.D=function(a){var b=n._sf_async_config;if(!a&&b&&b.noCookies)return i;if(U.D.Oa!==g)return U.D.Oa;var a=r()+"",c,d;try{if((d=n.localStorage).setItem(a,a),c=d.getItem(a)===a,d.removeItem(a),c)return U.D.Oa=d}catch(e){}return U.D.Oa=i};U.q=function(a){var b=U.D();if(!b)return"";var c=b.getItem(a+"_expires");return c&&(c=+c,!isNaN(c)&&r()>c)?(U.remove(a),""):b.getItem(a)||""};
U.create=function(a,b,c){var d=U.D();if(d){var e=new Date;e.setTime(r()+c*1E3);try{d.setItem(a,b),d.setItem(a+"_expires",e.getTime())}catch(f){}}};U.remove=function(a){var b=U.D();b&&(b.removeItem(a),b.removeItem(a+"_expires"))};function lb(a){this.Ga=a||"";this.Qb=U.D()!==i||S.Ob();this.bb=k;mb(this)}m=lb.prototype;m.isSupported=function(){return this.Qb};
function mb(a){if(!S.q("_cb_ls")){var b=U.D()!==i,c=S.q("_SUPERFLY_nosample");c&&q(["","_v_","_p_"],function(b){a.create(b+"_SUPERFLY_nosample",c,600,h)});var d=S.q("_chartbeat3");d&&(a.create("_v__chartbeat3",d,2592E3,h),S.remove("_chartbeat3"));b&&((b=S.q("_chartbeat2"))&&a.create("_chartbeat2",b,94608E3,h),(b=S.q("_chartbeat_uuniq"))&&a.create("_chartbeat_uuniq",b,94608E3,h),(b=S.q("_chartbeat5"))&&a.create("_chartbeat5",b,60,h));S.create("_cb_ls","1",2592E3)}}
function nb(a){var b=a.bb;a.bb=k;return b}m.create=function(a,b,c,d){a=d?a:this.Ga+a;(U.D()?U:S).create(a,b,c);U.D()&&S.create(a,b,c)};m.update=function(a,b,c,d,e,f,l){a=d?a:this.Ga+a;e=B(e)?e:"::";d=(d=this.q(a,h))?d.split(e):[];if(l&&d.length){var j=l(b),o=ja(d,function(a){return l(a)===j});o!==-1&&d.splice(o,1)}z(f)&&d.length>=f&&d.splice(0,d.length-f+1);d.push(b);this.create(a,d.join(e),c,h)};
m.q=function(a,b){var a=b?a:this.Ga+a,c=(U.D()?U:S).q(a);if(!c&&U.D()&&(c=S.q(a))&&S.q("_cb_ls")){this.bb=h;var d;switch(a){case "_SUPERFLY_nosample":d=600;break;case "_chartbeat4":d=3600;break;case "_cb_cp":d=3600;break;case "_chartbeat3":d=2592E3;break;default:d=94608E3}U.create(a,c,d)}return c};m.remove=function(a,b){a=b?a:this.Ga+a;(U.D()?U:S).remove(a);U.D()&&S.remove(a)};function ob(a){var b=i;if(a&&(b=pb()))return b;var c=n.location,b=V(c.pathname),a=c.search||"",a=a.replace(/PHPSESSID=[^&]+/,""),d=/&utm_[^=]+=[^&]+/ig;(c=d.exec(c.search))&&(a=a.replace(d,""));d=/\?utm_[^=]+=[^&]+(.*)/i;(c=d.exec(a))&&(a=a.replace(d,c[1]!=""?"?"+c[1]:""));return b+a}function pb(){var a=i;q(document.getElementsByTagName("link"),function(b){if(b.rel=="canonical")return b=Ra(b.href),a=V(b.pathname)+b.search+b.hash,k});return a}
for(var qb={},rb=0;rb<81;rb++)qb["0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-._~!$&'()*+,;=:@[]".charCodeAt(rb)]=h;function sb(a,b){if(a==="%")return"%25";var c=parseInt(b,16);return qb[c]?String.fromCharCode(c):"%"+b.toUpperCase()}function V(a){if(!B(a))return a;a=a.replace(/%([0-9A-Fa-f]{2})?/g,sb);return a=a.replace(/[^0-9A-Za-z\-._~!$&'()*+,;=:@\/\[\]?#%]+/g,encodeURIComponent)};function W(){L.call(this);this.ca=[];this.B=new lb(this.Ab);this.G=new db;this.Ya=s(this.ga,this);y(n,"unload",this.Ya);Ma(s(this.k,this))}aa(W,L);m=W.prototype;m.Ha=h;
m.k=function(){W.Q.k.call(this);this.Ba=this.Y=0;this.ia=r();this.ra=p(tb(this));var a=(this.B.q("_chartbeat2",h)||"").split("."),b=r(),c=b-+(a[1]||0);b-=+(a[2]||0);this.ic=a[0]&&c>18E5&&b<2592E6?0:1;this.ha=h;this.Ca=72E5;if(this.Ha&&(a=+this.a.sessionLength,!isNaN(a)))this.Ca=a*6E4;a=(this.B.q("_chartbeat2",h)||"").split(".");a.length>4&&(a=[]);var c=r(),d="1",e=a&&+a[2],b=a&&a[3];if(a&&e&&b)if(d=Math.abs((ga(c)-ga(e))/864E5)){d=Math.min(d,16)-1;for(e="";d--;)e+=0;d=(b+e+"1").slice(-16)}else d=
b;b=d;a[0]||(a[0]=this.a.utoken||p(tb(this),3),a[1]=c);a[2]=c;a[3]=b;this.La=a[0];this.oc=a.join(".");this.B.create("_chartbeat2",this.oc,94608E3,h);this.a.utoken=this.La;var f;c=+a[1];b=+a[2];if((a=a[3])&&c&&b)f=(Math.min((Math.abs((ga(b)-ga(c))/864E5)||0)+1,16,a.length)-1).toString(16),f+=("0000"+parseInt(a,2).toString(16)).slice(-4);this.pb=f;this.G.k();P.k();I.k();Aa||(Ba=Ka(),Ca&&n.document.addEventListener&&n.document.addEventListener(Ca,La,k),Ja("focus","onfocusin",Ha),Ja("blur","onfocusout",
Ia),Ba&&Ha(),Aa=h);this.na=0;this.Hb=F(ya,this.Xa,this)};function ub(a){if(!a.B.q("_SUPERFLY_nosample")&&!Fa)a.hc?a.Ia():(a.hc=h,!n._sf_async_config&&!n._cbq?(a.Ea=s(a.Ia,a),y(n,"load",a.Ea)):a.Ia())}m.Ia=function(){var a=n._sf_startpt,b=n._sf_endpt;if(z(a))this.Za=z(b)?b-a:r()-a;I.k();this.Ua=setInterval(s(this.oa,this),15E3);this.oa()};
m.oa=function(){var a=this.G.fa,a=this.a.reading&&+this.a.reading||a>0;if(this.Ba<this.Y&&!a)this.Ba++;else{var b;if(na===g)b=n.navigator.userAgent,na=b.indexOf("AppleWebKit")>0&&b.indexOf("FBIOS")>0;b=na;b&&!a?this.Ba++:(a?this.Y=0:vb(this),this.Ba=0,this.ca.push(0),this.ca.length>18&&this.ca.shift(),this.Ha&&r()-this.ia>=this.Ca?this.terminate():this.T())}};
function wb(a){var b={};b.g=a.a.uid;b.g0=Va(a.a,"sections");b.g1=Va(a.a,"authors");b.g2=Va(a.a,"zone");b.g3=Va(a.a,"sponsorName");b.g4=Va(a.a,"type");!a.a.noCookies&&a.B.isSupported()?b.n=a.ic:b.nc=1;b.c=Math.round((r()-a.ia)/600)/100;b.E=a.G.S;var c=xb(a);a.na=Math.max(a.na,c);b.x=c;b.m=a.na;b.y=ta("Height");b.o=ta("Width");b.w=sa();b.b=a.Za?a.Za:"";if(a.pb)b.f=a.pb;b[""]=Wa(a.a);b.t=a.ra;b.V=54;b.tz=(new Date).getTimezoneOffset();b.sn=a.Fa;return b}
m.xb=function(){this.ca.push(1);var a=0;q(this.ca,function(b){a+=b});a<3?(this.ha=h,vb(this)):(this.terminate(),this.B.create("_SUPERFLY_nosample","1",600))};m.ga=function(){};m.Xa=function(){var a=xb(this);this.na=Math.max(this.na,a)};function xb(a){return qa("Y","Top",!!a.a.scrollElement)}function vb(a){var b=a.Y,b=b?Math.min(b*2,16):1;a.Y=b}
m.Ma=function(a,b){if(!Fa)this.ga(),this.terminate(),this.wa=n.location.protocol+"//"+this.a.domain+this.a.path,this.a.path=V(a),b&&(this.a.title=b),this.k(),ub(this)};function yb(a){if(a.wa)return h;a=(document.referrer||"").indexOf("://"+n.location.hostname+"/");return a!=-1&&a<9}function zb(a){a=a.wa;if(!a&&(a=document.referrer||"")){var b=Ra(a);if(b.protocol==="http:"||b.protocol==="https:")b.pathname=V(b.pathname),a=Sa(b)}return encodeURIComponent(a)}
function Ab(a){a=a.a.title.slice(0,100);return encodeURIComponent(a)}function tb(a){a=[zb(a),ta("Width"),ta("Height")];return ea(a)}function Bb(a){var b=[],c=a.B.q("_chartbeat4");c&&(q(c.split("::"),function(a){b.push(encodeURIComponent(a))}),a.B.remove("_chartbeat4"));return b}m.terminate=function(){this.G.terminate();G(this.Hb);this.Ea!==g&&fa("load",this.Ea);clearInterval(this.Ua)};
m.O=function(){this.terminate();fa("unload",this.Ya);this.Ya=this.Ea=this.B=this.ca=this.a=i;this.G.O();this.G=i;W.Q.O.call(this)};function Cb(){this.sa=Ta();if(this.sa!==0)this.a=n._sf_async_config||{},Db(this)}
function Db(a){if(a.sa===1){var b=n.document.createElement("div");b.setAttribute("style","position:fixed; left:0; right:0 ;top:0 ;bottom:0; background-color: rgba(0, 0, 0, 0.3); z-index:1000;");n.document.body.appendChild(b);var c=n.document.createElement("div");n.document.body.appendChild(c);var d=a.a;q(["sections","zone","sponsorName","type"],function(a){if(d[a]!==g){var b=n.document.createElement("div");b.textContent=a+": "+d[a];c.appendChild(b)}});c.children.length&&(a="background-color: #F1F7FB; z-index: 9000000; position: fixed;padding: 10px; border-radius: 5px; font-size: 12px;color: #658BA1; border: 1px solid #C8DAE8;font-family: 'Proxima-Nova','Helvetica Neue',Helvetica,Arial,sans-serif;top: "+
Math.round(sa()*0.9)+"px;left: "+Math.round(ra("Width")*0.45)+"px;",c.setAttribute("style",a))}};function Eb(a){var b=Fb();return t(g)&&!t(b[a])?g:b[a]}function Fb(){t(n._cb_shared)||(n._cb_shared={});return n._cb_shared};function X(){this.U=[];this.$a=[];this.Aa=s(this.Aa,this);"postMessage"in window&&y(window,"message",s(this.cc,this));this.Ab="_p_";this.Ha=k;y(n,"beforeunload",s(this.lc,this));(this.sa=Ta()>0)&&new Cb;W.call(this)}aa(X,W);
X.prototype.k=function(){X.Q.k.call(this);var a=n.location;M(this.a,"pingServer","ping.chartbeat.net");M(this.a,"endServer","edge01.chartbeat.net");M(this.a,"title",document.title);M(this.a,"domain",a.hostname);M(this.a,"path",ob(!!this.a.useCanonical));M(this.a,"engaged",k);this.ya=this.a.adIdentifier||"data-cb-ad-id";this.a.domain=x(this.a.domain);this.Z=this.B.q("_chartbeat2",h);this.da=this.sb=0;this.Wb=function(){var a=r()-this.sb;a<500?(this.da&&n.clearTimeout(this.da),this.da=n.setTimeout(s(this.T,
this),500-a)):this.ha||this.T()};this.Vb=F("p",this.Wb,this);if(!this.Z)this.a.utoken?this.Z=this.a.utoken:(this.Z=p(tb(this),3),this.a.utoken=this.Z);this.Z=this.Z.split(".")[0];this.ua();if((a=this.a.engagedAdFilters)&&a.length){this.a.engagedAdFilters=[];var b=this;q(a,function(a){b.xa(a)})}this.Tb=F("e",this.Sb,this);this.zc=F("z",this.vc,this);this.$a=[]};X.prototype.lc=function(){this.T(h)};
X.prototype.ga=function(){this.B.update("_chartbeat4",["t="+this.ra,"E="+this.G.S,"ad="+ha(Gb(this,h)),"x="+xb(this),"c="+Math.round((r()-this.ia)/600)/100,"y="+ta("Height"),"w="+sa()].join("&"),3600,g,g,1)};function Gb(a,b){var c=[];q(a.U,function(a){a=fb(a);(!b||!(a.aw<=1&&a.ah<=1))&&c.push(kb(a))});return c.concat(a.$a).join("&")}var Hb="h,p,u,d,g,g0,g1,g2,g3,g4,n,nc,f,c,x,m,y,o,w,j,E,v,r,vp,b,t,V,i,tz,l,,ad,z,zz,sn".split(",");m=X.prototype;
m.T=function(a){this.Fa++;var b=this.Aa();b.ad=ha(Gb(this));this.sb=r();this.da&&n.clearTimeout(this.da);ob(!!this.a.useCanonical);if(this.ha)this.ha=k,b.i=Ab(this);this.wa&&(b.vp=1);var c=0;a?(b.zz=1,a=this.a.endServer):(b.z=Bb(this),c=Math.round((this.Y+2)*15E3/1E3),a=this.a.pingServer);b.j=c;b.l=nb(this.B)?1:"";this.G.fa=0;this.qa("https://"+a+"/ping/ad?"+Qa(b,Hb))};
m.Aa=function(){var a=wb(this),b=n.location;a.h=encodeURIComponent("ads."+this.a.domain);a.p=encodeURIComponent(this.a.path);a.u=this.Z;a.d=ha(x(b.hostname));yb(this)?a.v=zb(this):a.r=zb(this);return a};function Ib(a){var b=oa(a.ya,"div");q(b,function(b){if(!Jb(a,b)){var d=new Q(b,a.Aa,a.sa);a.U.push(d);d.ua();if(b=D("data-cb-engaged-seconds",b))d=hb(d),d.engagedSeconds=parseInt(b,10),a.xa(d)}})}function Jb(a,b){var c=k;q(a.U,function(a){if(a.F===b)return c=h,k});return c}
m.ua=function(){var a=Eb("c");Ib(this);var b=this;q(this.U,function(c){c.ua();var d=c.M;if(a&&a[d]){var e=-1;q(a[d],function(a,d){if(a.e===c.F)return a.c(b.ra),e=d,k});e>-1&&a[d].splice(e,1)}})};m.Xa=function(){X.Q.Xa.call(this);Ib(this)};m.cc=function(a){this.tb(la(a.data),a.source)};
m.tb=function(a,b){if(a.cbType!=="campaignMessage")return k;var c=b;if(c.parent!=window){for(var d=0;c.parent!=window&&d<10;)c=c.parent,d++;if(d>=10)return k}Ib(this);var d=document.getElementsByTagName("iframe"),e=g;q(d,function(a){if(a.contentWindow===c)return e=a,k});if(!e)return k;var f=e.getAttribute(this.ya),l;if(f===i){l=pa(e,this.ya);if(!l)return k;f=l.getAttribute(this.ya)}else l=e;var j=g;q(this.U,function(a){if(f===a.M&&l===a.F)return j=a,k});if(j===g)return k;jb(j,a,e);if(a.exclude)j.Qa=
h;if(a.engagedSeconds)d={id:j.M},d.campaignId=a.campaignId,d.creativeId=a.creativeId,d.engagedSeconds=parseInt(a.engagedSeconds,10),this.xa(d);d="cbdata::ack::"+this.ra;"postMessage"in b&&b.postMessage(d,"*");return d};m.Ma=function(){this.ga();this.terminate();this.wa=n.location.protocol+"//"+this.a.domain+this.a.path};
m.xa=function(a){if(a&&z(a.engagedSeconds)&&!isNaN(a.engagedSeconds)){var b=this.a.engagedAdFilters;if(!b||b.length===g)this.a.engagedAdFilters=[],b=this.a.engagedAdFilters;var c={};c.engagedSeconds=a.engagedSeconds;q(["id","campaignId","creativeId"],function(b){B(a[b])&&(c[b]=a[b])});var d=k;q(b,function(a){d=ia(a,c);return!d});d||b.push(c)}};
m.Sb=function(a,b){var c=this.a.engagedAdCallback;if(c){var d=this.a.engagedAdFilters;if(d&&d.length&&a){var e=a.engagedSeconds;q(d,function(d){if(d.engagedSeconds===e){var l=h;q(d,function(b,c){return l=b===a[c]});if(l)return a.element=b,c(a,e),k}})}}};m.pc=function(a){if(a){var b;q(this.U,function(c){if(c.M===a||c.F===a)return b=c,k});if(b){var c=fb(b);c.aR="1";this.$a.push(kb(c));b.reset()}}};
m.vc=function(a,b){for(var c=la(this.B.q("_chartbeat7")),d=parseInt(c[a.vzcid],10)||0,e={1:h,5:h,15:h,30:h,60:h,100:h};b--;)if(d++,e[d+""]){var f=a,l=d+"second"+(d!==1?"s":""),j=p(ca());ba("http://ohlone.vizu.com/a.gif?vzcid="+f.vzcid+"&vzadid="+l+"&vzsid="+f.vzsid+"&ord="+j)}c[a.vzcid]=d;this.B.create("_chartbeat7",ka(c),94608E3)};m.terminate=function(){G(this.Vb);G(this.Tb);G(this.zc);q(this.U,function(a){a.O()});this.U=[];n.clearTimeout(this.da);X.Q.terminate.call(this)};if(!n.pSUPERFLY_pub){var Kb=new X;n.pSUPERFLY_pub=Kb;X.prototype.virtualPage=X.prototype.Ma;X.prototype.addEngagedAdFilter=X.prototype.xa;X.prototype.refreshAd=X.prototype.pc;X.prototype.updateCampaignData=X.prototype.ua;if("postMessage"in window!==h)X.prototype.loadCampaign=X.prototype.tb;ub(Kb)};function Lb(){var a=document.createElement("script");a.async=h;a.src=(n.location.protocol||"http:")+"//static.chartbeat.com/js/inpage.js";var b=document.getElementsByTagName("head");b&&b.length&&b[0].appendChild(a)}function Mb(a){if(/[\/|\.]chartbeat\.com$/.test(a.origin)){var b=U.D(h),c=String(a.data);b&&c.indexOf("_cb_ip")==0&&(b.setItem("_cb_ip","1"),a.source.postMessage(1,a.origin),Lb())}};function Nb(a,b){for(var c=b||document.documentElement,d=[],e=i,f=a,l,j,o,w,v,J;f&&f!==c;){l=f.nodeName.toLowerCase();e=f;j=e.nodeName;if((f=f.parentNode)&&f!==document.documentElement){o=f.children;w=0;for(v=0,J=o.length;v<J;v++){if(e===o[v]){l+="["+(1+v-w)+"]";break}o[v].nodeName!==j&&w++}}d.unshift(l)}return d.join("/")};function Z(){"postMessage"in window&&y(n,"message",s(this.bc,this));W.call(this);for(var a=s(this.yb,this),b=n._cbq||[];b.length;)a(b.shift());n._cbq={push:a}}aa(Z,W);
Z.prototype.k=function(){Z.Q.k.call(this);this.Na=i;Ua(this.a);var a=n.location;M(this.a,"pingServer","ping.chartbeat.net");M(this.a,"title",document.title);M(this.a,"domain",a.hostname);this.a.path=this.a.path?V(this.a.path):ob(!!this.a.useCanonical);this.la=x(a.hostname);this.a.domain=x(this.a.domain);this.Mb=F("c",this.jc,this);this.Nb=F("r",this.kc,this);this.ea=i};Z.prototype.Gb=function(a){this.Na=a};
Z.prototype.ga=function(){this.B.update("_chartbeat4",["t="+this.ra,"E="+this.G.S,"x="+xb(this),"c="+Math.round((r()-this.ia)/600)/100,"y="+ta("Height"),"w="+sa()].join("&"),3600,g,g,1)};var Ob="h,p,u,d,g,g0,g1,g3,g4,n,nc,f,c,x,m,y,o,w,j,R,W,I,E,e,v,r,vp,K,l1,KK,PA,b,A,_c,_m,t,V,z,i,L,tz,l,,sn,C".split(",");m=Z.prototype;
m.T=function(a){this.Fa++;var b=wb(this),c=this.G.fa;b.h=encodeURIComponent(this.a.domain);b.p=encodeURIComponent(this.a.path);b.u=this.La;b.d=encodeURIComponent(this.la);b.j=Math.round((this.Y+2)*15E3/1E3);b.R=0;b.W=0;b.I=0;I.Jb()?b.W=1:this.a.reading&&+this.a.reading||c>0||b.c<0.09?b.R=1:b.I=1;b.e=c;c=yb(this);if(this.ha){this.ha=k;c?this.ea=Pb(this):b.r=zb(this);b.i=Ab(this);var d=this.a.hudTrackable;d!==g&&(b.L=d?"1":"0");this.a.alias&&(b.PA=encodeURIComponent(this.a.alias))}if(c){if(this.ea){if(b.v=
encodeURIComponent(this.ea.path),b.K=Qb(this.ea),this.ea.Wa>1)b.l1=this.ea.Wa}else b.v=zb(this);this.wa&&(b.vp=1)}b.A=this.Na?this.Na:"";b._c=Oa("utm_campaign",this.a.campaignTag);b._m=Oa("utm_medium",this.a.mediumTag);b.z=Bb(this);b.C=this.a.mobileApp?1:"";b.KK=a?Qb(a,h):"";b.l=nb(this.B)?1:"";this.G.fa=0;this.qa((n.location.protocol||"http:")+"//"+this.a.pingServer+"/ping?"+Qa(b,Ob))};
m.bc=function(a){var b=this.a;if(a.origin==="http://"+(b.playerdomain||this.la)){var c=a.data;B(c)&&c.indexOf("cbqpush::")===0?(a=c.split("::"),a.length==3&&(a=a.slice(1),a[0].indexOf("_")===0&&this.yb(a))):c=="cbdata?"&&(b="domain="+encodeURIComponent(b.domain)+"&uid="+encodeURIComponent(b.uid)+"&path="+encodeURIComponent(b.path)+"&title="+Ab(this)+"&referrer="+zb(this)+"&internal="+(yb(this)?"1":"0")+"&subdomain="+encodeURIComponent(this.la)+"&utoken="+this.La,a.source.postMessage(b,"*"))}};
m.yb=function(a){a[0]==="_demo"&&this.a._demo?this.a._demo=this.a._demo+"%2C"+a[1]:this.a[a[0]]=a[1];this.Y=0};function Rb(a){a=a.replace(/-{2,}/g,"-");a=Ra(a);a.pathname=V(a.pathname);return a}m.jc=function(a){Sb(this,a,"c")};m.kc=function(a){Sb(this,a,"r")};
function Sb(a,b,c){if(a.Ha&&r()-a.ia>=a.Ca)a.terminate();else{var d=b.href||"",d=Rb(d);if(!(d.hostname!==n.location.hostname||d.protocol.indexOf("http")!==0)){var d=Sa(d),e=ua(b,function(a){return a.id}),f=Nb(b,e);e&&(f&&(f="/"+f),f="*[@id='"+e.id+"']"+f);e=p(f);b=ab(b,g,h);c={left:b.x,top:b.y,path:a.a.path,href:d,gb:e,fb:f,ab:c,Wa:0};a.T(c);a.B.update("_chartbeat5",Tb(c),60,k,g,5,function(a){a=a.split(",");return a[2]+","+a[3]})}}}
function Qb(a,b){var c=[a.left,a.top,a.gb,encodeURIComponent(a.fb),a.ab];b&&c.push(encodeURIComponent(a.href));return c.join("::")}function Tb(a){var b=encodeURIComponent(a.fb),b=b.replace(/-/g,"%2D");b.length>512&&(b="");return[a.left,a.top,encodeURIComponent(a.path),encodeURIComponent(a.href),a.gb,b,a.ab].join(",")}
function Pb(a){var b=a.B.q("_chartbeat5");if(!b)return i;var c=b.split("::"),b=c.length,d,e;if(b===1)d=c[0].split(","),e=0;else{var f,l=Rb(n.location.href),j=Sa(l);q(c,function(a,b){var c=a.split(","),l=ma(j,decodeURIComponent(c[3]));if(l===0)return d=c,e=b,k;if(f===g||l<f)f=l,d=c,e=b})}c.splice(e,1);a.B.create("_chartbeat5",c.join("::"),60);(a=d[5])?(a=a.replace(/%2D/g,"-"),a=decodeURIComponent(a)):a="";return{left:d[0],top:d[1],path:decodeURIComponent(d[2]),gb:d[4]||"",fb:a,ab:d.length>6?d[6]:"c",
Wa:b}}m.terminate=function(){G(this.Mb);G(this.Nb);Z.Q.terminate.call(this)};if(!n.pSUPERFLY){var Ub=new Z;n.pSUPERFLY=Ub;Z.prototype.virtualPage=Z.prototype.Ma;Z.prototype.activity=Z.prototype.Gb;var $=n.pSUPERFLY_pub;$&&$.virtualPage&&(Z.prototype.virtualPage=function(){var a=arguments.length?Array.prototype.slice.call(arguments,0):[];$.virtualPage();Z.prototype.Ma.apply(Ub,a);$.k();ub($)});$&&$.addEngagedAdFilter&&(Z.prototype.addEngagedAdFilter=s($.addEngagedAdFilter,$));$&&$.refreshAd&&(Z.prototype.refreshAd=s($.refreshAd,$));ub(Ub);var Vb=U.D(h);if(Vb){y(n,"message",
Mb);var Wb;if(Wb=Vb.getItem("_cb_ip")){var Xb=n.location;Wb=!(!/^([^.]+[.])?chartbeat\.com$/.test(Xb.hostname)?0:/^\/publishing\/(overlay|hud|mab)\//.test(Xb.pathname))}Wb&&Lb()}};function Yb(){var a=n.location.href,a=a.replace(/-{2,}/g,"-"),a=Ra(a);a.pathname=V(a.pathname);return a}function Zb(a){var b=S.q("_chartbeat6");if(!b)return i;var b=b.split("::"),c,d;if(b.length===1)c=b[0].split(","),d=0;else{var e,f=Yb(),l=Sa(f);q(b,function(a,b){var f=a.split(","),v=ma(l,decodeURIComponent(f[0]));if(v===0)return c=f,d=b,k;if(e===g||v<e)e=v,c=f,d=b})}b.splice(d,1);a="_chartbeat6="+b.join("::")+$b(a);document.cookie=a;return{Cc:c[0],Ub:c[1],wc:c[2],origin:c[3]}}
function $b(a){var b="",c;if(!C(a))return b;a.vb&&(c=new Date,c.setTime(c.getTime()+a.vb),b+="; expires="+c.toGMTString());a.domain&&(b+="; domain="+a.domain);a.path&&(b+="; path="+a.path);return b}function ac(a,b){if(a===b)return h;for(var c=b.split("."),d=a.split(".");c.length;){if(d.length===0)return k;if(c.pop()!==d.pop())return k}return h};function bc(){this.Ab="_t_";W.call(this)}aa(bc,W);m=bc.prototype;
m.k=function(){bc.Q.k.call(this);Ua(this.a);var a=n.location;M(this.a,"mabServer","mabping.chartbeat.net");M(this.a,"title",document.title);M(this.a,"domain",a.hostname);M(this.a,"path",ob(!!this.a.useCanonical));this.la=x(a.hostname);this.a.domain=x(this.a.domain);var b=this.a,a=b.topStorageDomain,b=b.domain,c=n.location.hostname;this.tc=a?a:ac(c,b)?b:c.replace(/^www\./,"");this.Cb=this.nb=this.ob="";this.za=this.Va=k;a=Zb({domain:"."+this.tc,vb:6E4,path:"/"});if(a!==i)this.ob=a.origin,this.nb=a.Ub,
this.Cb=a.wc,this.Va=h;this.Ca=6E4;this.wb=0;a=s(this.dc,this);for(b=Eb("m")||[];b.length;)a(b.shift());a={push:a};Fb().m=a};m.T=function(){var a=this.G.S,b=cc(this),c,d,e;if(this.Va)c=this.ob,d=this.nb,e=this.Cb,this.qa(b+"&x="+d+"&v="+e+"&xo="+c+"&e="+a);!this.za&&t(this.Bb)&&dc(this,this.Bb);this.za=h};m.Ia=function(){var a=n._sf_startpt,b=n._sf_endpt;if(z(a))this.Za=z(b)?b-a:r()-a;I.k();if(this.Va)this.Ua=n.setInterval(s(this.oa,this),500);this.oa()};
m.oa=function(){var a,b;this.za?(a=this.G.S,b=this.wb*15,a-b>=15&&(this.T(),this.wb+=1),a>=45&&n.clearInterval(this.Ua)):this.T()};function cc(a){var b=a.a;return(n.location.protocol||"http:")+"//"+b.mabServer+"/ping/mab?h="+encodeURIComponent(b.domain)+"&p="+encodeURIComponent(b.path)+"&d="+encodeURIComponent(a.la)+"&u="+a.La+"&c="+Math.round((r()-a.ia)/600)/100}m.ga=function(){};
m.sc=function(a){var b=a.d,c=i;b!==i&&(c={qc:b.s,gc:b.l});a={status:a.s,data:c,code:a.c,message:a.m};this.za?dc(this,a):this.Bb=a};function dc(a,b){var c=cc(a),d=b.status,e=b.data;if(d=="s"&&e!==i){if(!e.gc){var f=s(a.qa,a);q(e.qc,function(a,b){f(c+"&x="+b+"&v="+a+"&e=-1")})}}else d=="e"&&a.qa(c+"&type=error&te="+b.code)}m.dc=function(a,b){for(var c=0,d=arguments.length;c<d;c++)a=arguments[c],a.shift()==="t"&&this.sc.apply(this,a)};if(!n.pSUPERFLY_mab)n.pSUPERFLY_mab={},ub(new bc);})();
